### PR TITLE
collection_requirements.rst: add redirect to docs.ansible.com

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible/ansible/pull/80234

### CODE REVIEW

**Comment by Andersson007** [comment]
ready for review

**Review by felixfontein — COMMENTED** [review]
You also need to adjust the links in this repo to this file.

**Comment by Andersson007** [comment]
> You also need to adjust the links in this repo to this file.

Thanks, done, PTAL

**Review by felixfontein — APPROVED** [review]
LGTM. Once this is merged https://github.com/ansible-collections/ansible-inclusion/ needs an update as well

**Pull request merged**
